name: Build and deploy Python project to Azure Function App - kafkaeventblob

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies to local package folder
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x '*.git*' '*.venv*' '*.github*'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip build
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A8DF602EBAC480AA5716520D3AF8EDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DB37BED5AEF54EF4842DE18818535411 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5600650451384C4E8EF3E57CA1574A6F }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'kafkaeventblob'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#